FROM ubuntu:19.10

RUN apt-get update && apt-get install -y python3.7 python3-pip python3-setuptools
WORKDIR /code/musicpod
COPY requirements.txt /code/musicpod
RUN pip3 install --no-cache-dir -r requirements.txt
